### ISSUE TITLE
Wrong column in scoreboard in 03_compile_varimport_v2.R

### ISSUE THREAD

**Issue by magnuscar** [benkeser/vrc01#1]
Hi there, 
I am just trying your code for objective 2. In 03_compile_varimport_v2.R, I found that the column called by scoreboard$score.overall does not exist. Do you mean scoreboard$continuous.ic.endpoints instead?

**Comment by benkeser** [comment]
Thanks for the report. In the most recent commit, we have updated a number of scripts and READMEs that hopefully will make replicating the analysis easier. This repository involved pulling together code from four different individuals. We've done our best to fit the pieces together, but as you've found, some mistakes are possible in the way things are pieced together. If you come across any additional issues in the updated code, do let us know. Thanks again for bringing these bugs to our attention.
