### ISSUE TITLE
Non-existing files called in 04_varimport_omnibus_v2.R

### ISSUE THREAD

**Issue by magnuscar** [benkeser/vrc01#2]
Hi there, 
In 04_varimport_omnibus_v2.R, some data files are called that are either not provided or ar not produced yet. These are all files starting with "vimp_" in lines 24-28 and "vrc01_final_r1_all_v11.csv" called in line 33. Which files are actually meant there?
Many thanks for looking into this.
Carsten

**Comment by benkeser** [comment]
Thanks for the reports. We're looking into fixes.

**Comment by bdwilliamson** [comment]
Hi Carsten,

Thanks for the reports! I have updated the file 04_varimport_omnibus_v2.R to reference the appropriate data file (on line 33).

To your first point: the .csv files called from lines 22--27 are outputs from other R scripts in this directory. We're not going to provide those files, but you can replicate them by following the workflows described in the README file for objective 2.
